<p style="color: #E56717">WARN: prepare<br />
It seems that your USE_PYTHON setting lists different Python<br />
implementations than your PYTHON_TARGETS variable. Please consider<br />
using the following value instead:<br />
<br />
USE_PYTHON='[35m3.4 [1m2.7[0m'<br />
<br />
Please note that after changing the USE_PYTHON variable, you may need<br />
to run 'python-updater' to rebuild affected packages.<br />
<br />
For more information on PYTHON_TARGETS and python.eclass<br />
compatibility, please see the relevant Wiki article [1].<br />
<br />
[1] https://wiki.gentoo.org/wiki/Project:Python/PYTHON_TARGETS<br />
</p>